theme: jekyll-theme-slate
title: Zhuofan (Fan)'s Blogpost Page
email: zzhang433@gatech.edu
github_username: zhzhang2018
description: Current webpage for this current Georgia Tech graduate student, and Dartmouth and Colby alum.
